COA_NODE_GROUP_NAME = "COATools Material"

COA_VERSION = "2.0.0"

# draw type constants for gpu drawing
DRAW_LINE_STRIP = "LINE_STRIP"
DRAW_LINES = "LINES"
DRAW_POINTS = "POINTS"
DRAW_TRIS = "TRIS"
DRAW_LINE_LOOP = "LINE_LOOP"

SHADER_2D_UNIFORM_COLOR = "2D_UNIFORM_COLOR"
SHADER_3D_SMOOTH_COLOR = "3D_SMOOTH_COLOR"
SHADER_2D_SMOOTH_COLOR = "2D_SMOOTH_COLOR"

SHADER_UNIFORM_COLOR = "UNIFORM_COLOR"
SHADER_SNMOOTH_COLOR = "SMOOTH_COLOR"
