COA_NODE_GROUP_NAME = "COATools Material"

COA_VERSION = "2.0.0"

# draw type constants for gpu drawing
DRAW_LINE_STRIP = "LINE_STRIP"
DRAW_LINES = "LINES"
DRAW_POINTS = "POINTS"
DRAW_TRIS = "TRIS"
DRAW_LINE_LOOP = "LINE_LOOP"

SHADER_2D_UNIFORM_COLOR = "2D_UNIFORM_COLOR"
SHADER_3D_SMOOTH_COLOR = "3D_SMOOTH_COLOR"
SHADER_2D_SMOOTH_COLOR = "2D_SMOOTH_COLOR"

SHADER_FLAT_COLOR = 'FLAT_COLOR'
SHADER_IMAGE = 'IMAGE'
SHADER_COLOR = 'IMAGE_COLOR'
SHADER_SMOOTH_COLOR = 'SMOOTH_COLOR'
SHADER_UNIFORM_COLOR = 'UNIFORM_COLOR'
SHADER_POLYLINE_FLAT_COLOR = 'POLYLINE_FLAT_COLOR'
SHADER_POLYLINE_SMOOTH_COLOR = 'POLYLINE_SMOOTH_COLOR'
SHADER_POLYLINE_UNIFORM_COLOR = 'POLYLINE_UNIFORM_COLOR'