# .github/workflows/check-pr-source-master.yml
name: check-pr-source-master
on:
  pull_request:
    branches: [ master ]

jobs:
  validate_source:
    runs-on: ubuntu-latest
    steps:
      - name: source branch check
        if: >
          github.head_ref != 'prerelease'
        run: |
          echo "ERROR: Only prerelease branch can be merged into master."
          exit 1
