name: check-pr-source-prerelease

on:
  pull_request:
    branches:
      - prerelease

jobs:
  validate_source:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          if [ "${{ github.head_ref }}" != "develop" ] && [[ "${{ github.head_ref }}" != hotfix-* ]]; then
            echo "ERROR: Only develop and hotfix-* branches can be merged into prerelease."
            exit 1
          fi
